export const data = {
    es:{
        email:"Correo Electronico",
        password:"Contraseña",
        signin: "Iniciar Sesión",
        singout:"Salir",
        name:"nombre",
        es:"Español",
        en:"Ingles",
        new_meet:"Nueva meet!",
        day:"dia",
        add_meet:"Agregar meet",
        temp:"Temperatura",
        guests:"Invitados",
        boxes:"Cajas",
        beers:"Birras",
        save:"Guardar",
        cancel:"Cancelar",
        meet_list: "Listado de Meets",
        date:"Fecha",
        actions:"Acciones",
        check_in:"Check In",
        no_meets: "Sin meets agregadas",
        user:"Usuario"
    },
    en:{
        email:"Email Address",
        password:"Password",
        signin: "Sign In",
        singout: "Sign Out",
        name:"name",
        es:"Spanish",
        en:"English",
        new_meet:"New meet!",
        day:"day",
        add_meet:"Add meet",
        temp:"Temperature",
        guests:"Guests",
        boxes:"Boxes",
        beers:"Beers",
        save:"Save",
        cancel:"Cancel",
        meet_list: "Meets List",
        date:"Date",
        actions: "Actions",
        check_in:"Check In",
        no_meets: "No added meets",
        user:"User"
    }
}

